### ISSUE TITLE
API 43 not available

### ISSUE THREAD

**Issue by jgsousa** [forcedotcom/RecordViewer#49]
I was trying to do the Install Sample App step of the User Interface API Module, and it threw errors of 404 not found. I changed the api back to 42 and now it works. 

In my developer account and playgrounds the 43 version is not available yet.

**Comment by jpearson-sfdc** [comment]
@jgsousa - That's correct. Summer '18 Major Release (v43.0) is currently being deployed which means that some customers may have the update already while others will be receiving it soon. The workaround is as you've described (changed the API from 43.0 to 42.0).

See the schedule of deployments within the Maintenance Calendar.
https://status.salesforce.com/products/all/maintenances
